=pod 

=head1 NAME

clrasta - Command-line interface to the RASTA system.

=head1 SYNOPSIS

    clrasta [--file <system_file>] [<fastpath>]

    clrasta --help

=head1 DESCRIPTION

B<clrasta> is a program that reads a description file that specifies
screens and paths among those screens.  B<clrasta> allows the user
to make the choices and inputs described, and then runs an action with
these values on behalf of the user.

=head1 OPTIONS

=over 4

=item B<--file E<lt>system_fileE<gt>> 

Specifies the description file to read and use.  This defaults to
Z<>@RASTA_DIR@/system.rasta.

=item B<E<lt>fastpathE<gt>>

A fastpath is a known screen.  When specified, B<clrasta> will try
to start at the given screen rather than at the very top of the path.

=item B<--load-push>

Test push-loading of the system file.

=item B<--help>

Display help text and exit.

=item B<--version>

Display version and exit.

=back

=head1 BUGS

Surely some.

=head1 SEE ALSO

L<gtkrasta(2)> L<cgirasta>

=head1 VERSION

B<clrasta> version Z<>@VERSION@ (30 November 2001)

=head1 HISTORY

=over 4

=item Version 0.1.0

Initial version.

=back

=head1 AUTHOR

Joel Becker        E<lt>joel.beckerZ<>@oracle.comE<gt>

=head1 COPYRIGHT

Copyright E<169> 2001 Oracle Corporation, Joel Becker.
All rights reserved.

This program is free software; see the file COPYING in the source
distribution for the terms under which it can be redistributed and/or
modified.

=cut
