=pod 

=head1 NAME

rastaedit - Edit RASTA description files

=head1 SYNOPSIS

	rastaedit <system_file>

=head1 DESCRIPTION

B<rastaedit> is a program that reads a description file that specifies
screens and paths among those screens.  B<rastaedit> allows the user
to edit those files in a convenient manner.

=head1 BUGS

Surely some.

=head1 SEE ALSO

L<rastaadd(1)> L<rastadel(1)>

=head1 VERSION

B<rastaedit> version Z<>@VERSION@ (30 November 2001)

=head1 HISTORY

=over 4

=item Version 0.1.0

Initial version.

=back

=head1 AUTHOR

Joel Becker        E<lt>joel.beckerZ<>@oracle.comE<gt>

=head1 COPYRIGHT

Copyright E<169> 2001 Oracle Corporation, Joel Becker.
All rights reserved.

This program is free software; see the file COPYING in the source
distribution for the terms under which it can be redistributed and/or
modified.

=cut
